services:
  - type: web
    name: auditions-scoring-api
    env: node
    rootDir: server
    plan: free
    autoDeploy: true
    healthCheckPath: /api/debug/collections
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: PORT
        value: 4001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ARYAN_PASSWORD
        sync: false
      - key: KUNAL_PASSWORD
        sync: false
